#!/bin/busybox sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
exec >/dev/console 2>&1
echo DOXA_BROKER_VM_START
/bin/busybox mkdir -p /run/doxa-semantic
/bin/busybox chmod 755 /run/doxa-semantic
/broker_fixture &
broker_pid=$!
/bin/busybox sleep 1
/bin/busybox su guest -s /bin/sh -c '/codegraph-test disposable_guest_root_peer_identity_proof --ignored --nocapture'
test_status=$?
if [ "$test_status" -ne 0 ]; then
  /bin/busybox kill "$broker_pid"
fi
wait "$broker_pid"
broker_status=$?
echo DOXA_BROKER_TEST_STATUS="$test_status" BROKER_STATUS="$broker_status"
/bin/busybox poweroff -f
