#!/bin/busybox sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
exec >/dev/console 2>&1
echo DOXA_QUOTA_VM_START
/bin/busybox insmod /lib/modules/quota_tree.ko
echo DOXA_MODULE_QUOTA_TREE_STATUS=$?
/bin/busybox insmod /lib/modules/quota_v2.ko
echo DOXA_MODULE_QUOTA_V2_STATUS=$?
/bin/busybox insmod /lib/modules/virtio-rng.ko
echo DOXA_MODULE_VIRTIO_RNG_STATUS=$?
/bin/busybox sleep 1
/guest_harness
status=$?
echo DOXA_QUOTA_VM_STATUS=$status
/bin/busybox poweroff -f
