#!/bin/busybox sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
/bin/busybox mkdir -p /sys/fs/cgroup /run
/bin/busybox mount -t cgroup2 cgroup2 /sys/fs/cgroup
exec >/dev/console 2>&1
echo DOXA_EGRESS_ORIGIN_GUEST_START
/egress-origin-guest
status=$?
echo DOXA_EGRESS_ORIGIN_VM_STATUS=$status
/bin/busybox poweroff -f
